#sms_item_widget
ITEM_IMAGE_WIDTH = 165
ITEM_IMAGE_HEIGHT = 115
ITEM_WIDGET_WIDTH = 165
ITEM_WIDGET_HEIGHT = 200
ITEM_TEXT_WIDTH = 128
#item_info_dialog
ITEM_DIALOG_WIDTH = 265
ITEM_DIALOG_HEIGHT = 311
ITEM_IMAGE_INDEX = 0
ITEM_NAME_INDEX = 1
ITEM_CATEGORY_INDEX = 2
ITEM_COUNT_INDEX = 3
ITEM_QUANTIFIER_INDEX = 4
ITEM_MODIFY_ACTION = 0
ITEM_ADD_ACTION = 1
